"""SecurityStack — KMS CMK, IAM roles, and Secrets Manager placeholders.

Roles are scoped as tightly as practical for a POC. Bedrock model access is
constrained to the Claude inference profiles + Titan embeddings the pipeline
uses. The Oracle credential secrets are created with placeholder values; the
real DB password host/port are written after the database comes up.
"""
from aws_cdk import (
    Stack,
    RemovalPolicy,
    aws_iam as iam,
    aws_kms as kms,
    aws_logs as logs,
    aws_secretsmanager as secretsmanager,
)
from constructs import Construct


class SecurityStack(Stack):
    def __init__(self, scope: Construct, cid: str, *, prefix: str, network, **kwargs):
        super().__init__(scope, cid, **kwargs)
        self.prefix = prefix

        # --- Customer-managed KMS key (S3 SSE-KMS, secrets) ------------------
        self.kms_key = kms.Key(
            self, "PocKey",
            alias=f"alias/{prefix}-key",
            description=f"{prefix} customer-managed key",
            enable_key_rotation=True,
            removal_policy=RemovalPolicy.DESTROY,  # POC
        )

        # --- Secrets ---------------------------------------------------------
        # Oracle app/admin credentials. Password auto-generated; host/port/dsn
        # are patched in after DatabaseStack by scripts/02_verify_oracle.sh.
        self.oracle_secret = secretsmanager.Secret(
            self, "OracleSecret",
            secret_name=f"{prefix}/oracle/admin",
            description="Oracle XE 21c connection details for the POC",
            encryption_key=self.kms_key,
            generate_secret_string=secretsmanager.SecretStringGenerator(
                secret_string_template=(  # nosec B106 - secret template only; the password is generated by Secrets Manager, not hardcoded
                    '{"username":"app_data","service":"XEPDB1",'
                    '"host":"TO_BE_SET","port":"1521"}'
                ),
                generate_string_key="password",
                # Alphanumeric only. The password flows through nested
                # shell -> docker exec -> sqlplus connect strings and SQL DDL;
                # punctuation (single quote, $, backtick, @, /, backslash,
                # space) breaks that quoting. exclude_punctuation removes ALL
                # of it at the source so no downstream escaping is needed.
                exclude_punctuation=True,
                password_length=24,
            ),
            removal_policy=RemovalPolicy.DESTROY,
        )
        acct = Stack.of(self).account
        region = Stack.of(self).region
        # Claude + Titan model/inference-profile ARNs the pipeline may invoke.
        bedrock_model_arns = [
            f"arn:aws:bedrock:{region}::foundation-model/anthropic.claude-*",
            f"arn:aws:bedrock:{region}::foundation-model/amazon.titan-embed-text-v2:0",
            f"arn:aws:bedrock:{region}:{acct}:inference-profile/us.anthropic.claude-*",
            # Cross-region inference fans out to sibling US regions.
            "arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-*",
            "arn:aws:bedrock:us-east-2::foundation-model/anthropic.claude-*",
            "arn:aws:bedrock:us-west-2::foundation-model/anthropic.claude-*",
        ]

        # --- Pipeline Lambda role -------------------------------------------
        self.pipeline_lambda_role = iam.Role(
            self, "PipelineLambdaRole",
            role_name=f"{prefix}-pipeline-lambda-role",
            assumed_by=iam.ServicePrincipal("lambda.amazonaws.com"),
            managed_policies=[
                iam.ManagedPolicy.from_aws_managed_policy_name(
                    "service-role/AWSLambdaVPCAccessExecutionRole"),
            ],
        )
        self.pipeline_lambda_role.add_to_policy(iam.PolicyStatement(
            sid="BedrockInvoke",
            actions=["bedrock:InvokeModel", "bedrock:InvokeModelWithResponseStream",
                     "bedrock:Converse", "bedrock:ConverseStream"],
            resources=bedrock_model_arns,
        ))
        self.pipeline_lambda_role.add_to_policy(iam.PolicyStatement(
            sid="BedrockKbSync",
            actions=["bedrock:StartIngestionJob", "bedrock:GetIngestionJob",
                     "bedrock:ListIngestionJobs"],
            resources=[f"arn:aws:bedrock:{region}:{acct}:knowledge-base/*"],
        ))
        self.oracle_secret.grant_read(self.pipeline_lambda_role)
        self.kms_key.grant_encrypt_decrypt(self.pipeline_lambda_role)

        # --- ECS task role (the .NET API) -----------------------------------
        self.ecs_task_role = iam.Role(
            self, "EcsTaskRole",
            role_name=f"{prefix}-ecs-task-role",
            assumed_by=iam.ServicePrincipal("ecs-tasks.amazonaws.com"),
        )
        self.oracle_secret.grant_read(self.ecs_task_role)
        self.kms_key.grant_decrypt(self.ecs_task_role)

        # --- ECS task EXECUTION role ----------------------------------------
        # Owned here (not auto-created by ApiStack) so the secret-read + KMS
        # grants live in SecurityStack. If ApiStack created it, granting it
        # read on the KMS-encrypted secret would make SecurityStack's key
        # policy reference an ApiStack role -> stack dependency cycle.
        self.ecs_execution_role = iam.Role(
            self, "EcsExecutionRole",
            role_name=f"{prefix}-ecs-execution-role",
            assumed_by=iam.ServicePrincipal("ecs-tasks.amazonaws.com"),
            managed_policies=[
                iam.ManagedPolicy.from_aws_managed_policy_name(
                    "service-role/AmazonECSTaskExecutionRolePolicy"),
            ],
        )
        # Needed to inject the Oracle secret as a container secret at task start.
        self.oracle_secret.grant_read(self.ecs_execution_role)
        self.kms_key.grant_decrypt(self.ecs_execution_role)

        # API container log group, owned here so the execution-role write grant
        # stays intra-stack (an ApiStack-created log group would back-reference
        # this SecurityStack role and cycle).
        self.api_log_group = logs.LogGroup(
            self, "ApiLogGroup",
            log_group_name=f"/{prefix}/dotnet-api",
            retention=logs.RetentionDays.ONE_WEEK,
            removal_policy=RemovalPolicy.DESTROY,
        )
        self.api_log_group.grant_write(self.ecs_execution_role)
        # Optional: let the API proxy Bedrock KB RetrieveAndGenerate for Q&A.
        # Split into two statements so each action set is scoped to its own
        # resource type (model ARNs vs. knowledge-base ARNs).
        self.ecs_task_role.add_to_policy(iam.PolicyStatement(
            sid="BedrockRetrieveInvokeModel",
            actions=["bedrock:InvokeModel"],
            # Scoped to the same Claude inference profiles + Titan ARNs used
            # elsewhere in this stack.
            resources=bedrock_model_arns,
        ))
        self.ecs_task_role.add_to_policy(iam.PolicyStatement(
            sid="BedrockRetrieveKb",
            actions=["bedrock:RetrieveAndGenerate", "bedrock:Retrieve"],
            # Scoped to all knowledge-base resources in this account/region.
            # TODO production: pin to the specific KB ARN once known, e.g.
            #   arn:aws:bedrock:{region}:{acct}:knowledge-base/<kb-id>
            resources=[f"arn:aws:bedrock:{region}:{acct}:knowledge-base/*"],
        ))

        # --- EC2 (Oracle) instance role -------------------------------------
        self.ec2_role = iam.Role(
            self, "OracleEc2Role",
            role_name=f"{prefix}-oracle-ec2-role",
            assumed_by=iam.ServicePrincipal("ec2.amazonaws.com"),
            managed_policies=[
                iam.ManagedPolicy.from_aws_managed_policy_name(
                    "AmazonSSMManagedInstanceCore"),
            ],
        )
        self.oracle_secret.grant_read(self.ec2_role)
        self.kms_key.grant_decrypt(self.ec2_role)

        # --- Bedrock KB service role ----------------------------------------
        self.bedrock_kb_role = iam.Role(
            self, "BedrockKbRole",
            role_name=f"{prefix}-bedrock-kb-role",
            assumed_by=iam.ServicePrincipal("bedrock.amazonaws.com"),
        )
        self.bedrock_kb_role.add_to_policy(iam.PolicyStatement(
            sid="KbInvokeEmbeddings",
            actions=["bedrock:InvokeModel"],
            resources=[
                f"arn:aws:bedrock:{region}::foundation-model/amazon.titan-embed-text-v2:0"],
        ))
        # The KB reads/writes the OpenSearch Serverless collection over the
        # data plane; without aoss:APIAccessAll the collection returns 403 and
        # KB creation fails. Scoped to the POC collection ARN.
        self.bedrock_kb_role.add_to_policy(iam.PolicyStatement(
            sid="KbAossDataPlane",
            actions=["aoss:APIAccessAll"],
            resources=[
                f"arn:aws:aoss:{region}:{acct}:collection/*"],
        ))
